# Generated by Django 5.0.1 on 2024-01-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0002_streamingplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='movie_list.streamingplatform'),
            preserve_default=False,
        ),
    ]
