# Generated by Django 5.0.1 on 2024-02-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0007_remove_review_avg_rating_remove_review_number_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descroption',
            new_name='description',
        ),
    ]
